name: Docker Image CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
env:
  IMAGE_NAME: particula-back-end
  BRANCH_NAME: notset 
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set branche name as image tag
      run: |
        # Strip git ref prefix from version
        BRANCH_NAME=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        
    - uses: actions/checkout@v2
    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: "${{ github.actor }}"
        password: "${{ secrets.GITHUB_TOKEN }}"
        image_name: vives-projectwerk-2-2020/back-end/particula-back-end
        image_tag: "${{ BRANCH_NAME }}"
        registry: docker.pkg.github.com
        
  deploy:
    name: deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.PATH }}
          docker-compose pull backend
          docker-compose up -d backend
