name: Docker Image CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]
env:
<<<<<<< HEAD
  IMAGE_NAME: particula-back-end
jobs:
=======
  IMAGE_NAME: particula-back-end 
jobs:  
>>>>>>> develop

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Branch name
      id: branchname
      run: |
<<<<<<< HEAD
        echo "::set-output name=branch::`echo '${{ github.ref }}' | sed -e 's,.*/\(.*\),\1,'`"        
=======
        echo "::set-output name=branch::`echo '${{ github.ref }}' | sed -e 's,.*/\(.*\),\1,'`"
            
>>>>>>> develop
    - uses: actions/checkout@v2
    - uses: whoan/docker-build-with-cache-action@master
      with:
        username: "${{ github.actor }}"
        password: "${{ secrets.GITHUB_TOKEN }}"
        image_name: vives-projectwerk-2-2020/back-end/particula-back-end
        image_tag: "${{ steps.branchname.outputs.branch }}"
        registry: docker.pkg.github.com
        
  deploy:
    name: deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.PATH }}
          docker-compose pull backend
          docker-compose up -d backend
